import { randomUUID } from "node:crypto";
import {
  chmod,
  lstat,
  mkdir,
  readFile,
  rename,
  rm,
  writeFile
} from "node:fs/promises";
import path from "node:path";

const GENERATED_ENV_HEADER = [
  "# Generated by Vibe64 from the Genesis Stack.",
  "# Do not edit. Configure project values in Vibe64 Env."
].join("\n");
const GIT_EXCLUDE_BEGIN = "# BEGIN Vibe64 managed environment files";
const GIT_EXCLUDE_END = "# END Vibe64 managed environment files";
const MANAGED_SOURCE_DIRECTORY_MODE = 0o2770;
const MANAGED_SOURCE_FILE_MODE = 0o660;

function dotenvValue(value = "") {
  const text = String(value ?? "");
  return text && /^[A-Za-z0-9_./:@+-]+$/u.test(text)
    ? text
    : JSON.stringify(text);
}

function generatedDotenv(environment = {}) {
  const assignments = Object.entries(environment)
    .filter(([key, value]) => /^[A-Za-z_][A-Za-z0-9_]*$/u.test(key) && typeof value === "string")
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([key, value]) => `${key}=${dotenvValue(value)}`);
  return `${GENERATED_ENV_HEADER}\n\n${assignments.join("\n")}${assignments.length ? "\n" : ""}`;
}

function generatedDotenvIsOwned(source = "") {
  return String(source || "").startsWith(`${GENERATED_ENV_HEADER}\n`);
}

async function optionalFile(filePath = "") {
  try {
    return await readFile(filePath, "utf8");
  } catch (error) {
    if (["ENOENT", "ENOTDIR"].includes(error?.code)) {
      return null;
    }
    throw error;
  }
}

async function assertProjectionPath(sourceRoot = "", relativePath = "") {
  const root = path.resolve(sourceRoot);
  const target = path.resolve(root, relativePath);
  if (!target.startsWith(`${root}${path.sep}`)) {
    const error = new Error(`Environment file escapes the project source: ${relativePath}.`);
    error.code = "vibe64_environment_file_outside_source";
    throw error;
  }
  let current = root;
  for (const part of relativePath.split("/")) {
    current = path.join(current, part);
    const entry = await lstat(current).catch((error) => {
      if (["ENOENT", "ENOTDIR"].includes(error?.code)) {
        return null;
      }
      throw error;
    });
    if (entry?.isSymbolicLink()) {
      const error = new Error(`Environment file path contains a symbolic link: ${relativePath}.`);
      error.code = "vibe64_environment_file_symlink";
      throw error;
    }
    if (!entry) {
      break;
    }
  }
  return target;
}

async function backupPath(filePath = "", now = new Date()) {
  const base = `${filePath}.vibe64-backup-${now.toISOString().replace(/[:.]/gu, "-")}`;
  for (let sequence = 0; ; sequence += 1) {
    const candidate = sequence === 0 ? base : `${base}-${sequence}`;
    const exists = await lstat(candidate).then(() => true).catch((error) => {
      if (["ENOENT", "ENOTDIR"].includes(error?.code)) {
        return false;
      }
      throw error;
    });
    if (!exists) {
      return candidate;
    }
  }
}

function gitExcludePattern(relativePath = "") {
  const normalizedPath = String(relativePath || "").replaceAll("\\", "/");
  return `/${[...normalizedPath]
    .map((character) => "\\ #!*?[]".includes(character) ? `\\${character}` : character)
    .join("")}`;
}

async function writeManagedGitExcludes(sourceRoot = "", relativePaths = []) {
  const gitDirectory = path.join(path.resolve(sourceRoot), ".git");
  const gitEntry = await lstat(gitDirectory).catch((error) => {
    if (["ENOENT", "ENOTDIR"].includes(error?.code)) {
      return null;
    }
    throw error;
  });
  if (!gitEntry?.isDirectory()) {
    const error = new Error("Project environment files require an ordinary local Git directory.");
    error.code = "vibe64_environment_git_directory_required";
    throw error;
  }

  const infoDirectory = path.join(gitDirectory, "info");
  const excludePath = path.join(infoDirectory, "exclude");
  const excludeEntry = await lstat(excludePath).catch((error) => {
    if (["ENOENT", "ENOTDIR"].includes(error?.code)) {
      return null;
    }
    throw error;
  });
  if (excludeEntry?.isSymbolicLink()) {
    const error = new Error("The repository's local Git exclude file is a symbolic link.");
    error.code = "vibe64_environment_git_exclude_symlink";
    throw error;
  }

  const existing = await optionalFile(excludePath) || "";
  const lines = existing.replace(/\r\n?/gu, "\n").split("\n");
  const begin = lines.indexOf(GIT_EXCLUDE_BEGIN);
  const end = lines.indexOf(GIT_EXCLUDE_END);
  if ((begin >= 0) !== (end >= 0) || (begin >= 0 && end < begin)) {
    const error = new Error("The repository's managed environment exclude block is invalid.");
    error.code = "vibe64_environment_git_exclude_invalid";
    throw error;
  }
  const preserved = begin >= 0
    ? [...lines.slice(0, begin), ...lines.slice(end + 1)]
    : lines;
  while (preserved.at(-1) === "") {
    preserved.pop();
  }
  const patterns = [...new Set(relativePaths.flatMap((relativePath) => [
    gitExcludePattern(relativePath),
    `${gitExcludePattern(relativePath)}.vibe64-backup-*`
  ]))].sort();
  const expected = [
    ...preserved,
    ...(preserved.length > 0 ? [""] : []),
    GIT_EXCLUDE_BEGIN,
    ...patterns,
    GIT_EXCLUDE_END,
    ""
  ].join("\n");
  if (existing === expected) {
    return;
  }

  await mkdir(infoDirectory, {
    mode: MANAGED_SOURCE_DIRECTORY_MODE,
    recursive: true
  });
  const temporaryPath = `${excludePath}.vibe64-${process.pid}-${randomUUID()}`;
  try {
    await writeFile(temporaryPath, expected, {
      mode: MANAGED_SOURCE_FILE_MODE
    });
    await chmod(temporaryPath, MANAGED_SOURCE_FILE_MODE);
    await rename(temporaryPath, excludePath);
  } catch (error) {
    await rm(temporaryPath, {
      force: true
    }).catch(() => null);
    throw error;
  }
}

async function writeGeneratedDotenv({
  environment = {},
  now = new Date(),
  relativePath = "",
  sourceRoot = ""
} = {}) {
  const filePath = await assertProjectionPath(sourceRoot, relativePath);
  const expected = generatedDotenv(environment);
  const existing = await optionalFile(filePath);
  let preservedPath = "";
  if (existing !== null && !generatedDotenvIsOwned(existing)) {
    preservedPath = await backupPath(filePath, now);
    await rename(filePath, preservedPath);
  }
  if (existing === expected && !preservedPath) {
    return {
      changed: false,
      format: "dotenv",
      path: relativePath,
      preservedPath: ""
    };
  }
  await mkdir(path.dirname(filePath), {
    mode: MANAGED_SOURCE_DIRECTORY_MODE,
    recursive: true
  });
  const temporaryPath = `${filePath}.vibe64-${process.pid}-${randomUUID()}`;
  try {
    await writeFile(temporaryPath, expected, {
      mode: MANAGED_SOURCE_FILE_MODE
    });
    await chmod(temporaryPath, MANAGED_SOURCE_FILE_MODE);
    await rename(temporaryPath, filePath);
  } catch (error) {
    await rm(temporaryPath, {
      force: true
    }).catch(() => null);
    if (preservedPath) {
      await rm(filePath, {
        force: true
      }).catch(() => null);
      await rename(preservedPath, filePath).catch(() => null);
    }
    throw error;
  }
  return {
    changed: true,
    format: "dotenv",
    path: relativePath,
    preservedPath
  };
}

async function materializeProjectEnvironmentFiles({
  environment = {},
  files = [],
  now = new Date(),
  sourceRoot = ""
} = {}) {
  if (!sourceRoot || !Array.isArray(files) || files.length === 0) {
    return [];
  }
  const declarations = files.map((file) => {
    if (file?.format !== "dotenv") {
      const error = new Error(`Unsupported project environment file format: ${file?.format || "(empty)"}.`);
      error.code = "vibe64_environment_file_format_unsupported";
      throw error;
    }
    return {
      format: file.format,
      path: String(file.path || "")
    };
  });
  await Promise.all(declarations.map((file) => assertProjectionPath(sourceRoot, file.path)));
  await writeManagedGitExcludes(sourceRoot, declarations.map((file) => file.path));
  const results = [];
  for (const file of declarations) {
    results.push(await writeGeneratedDotenv({
      environment,
      now,
      relativePath: file.path,
      sourceRoot
    }));
  }
  return results;
}

export {
  GENERATED_ENV_HEADER,
  generatedDotenv,
  generatedDotenvIsOwned,
  materializeProjectEnvironmentFiles
};
