import assert from "node:assert/strict";
import test from "node:test";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { access, readdir, readFile } from "node:fs/promises";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const APP_ROOT = path.resolve(__dirname, "../..");

const EXPECTED_APPLICATION_SCRIPTS = Object.freeze({
  "jskit:check": "jskit check",
  "jskit:update": "npx --yes @jskit-ai/jskit-catalog@latest update",
  verify: "npm run lint && npm run test && npm run test:client && npm run build && npm run verify:packages"
});

const REQUIRED_TOP_LEVEL_ENTRIES = Object.freeze([
  "AGENTS.md",
  "app.json",
  "bin",
  "config",
  "eslint.config.mjs",
  "favicon.svg",
  "index.html",
  "jsconfig.json",
  "package.json",
  "packages",
  "scripts",
  "server",
  "server.js",
  "src",
  "tests",
  "vite.config.mjs"
]);
const RECURSIVE_SOURCE_IGNORED_DIRECTORIES = new Set([
  "coverage",
  "dist",
  "node_modules",
  "templates"
]);

async function readPackageJson() {
  const packageJsonPath = path.join(APP_ROOT, "package.json");
  const raw = await readFile(packageJsonPath, "utf8");
  return JSON.parse(raw);
}

async function readTopLevelEntries() {
  const entries = await readdir(APP_ROOT, { withFileTypes: true });
  const ignored = new Set([
    "node_modules",
    "dist",
    "coverage",
    "test-results",
    "package-lock.json",
    "pnpm-lock.yaml",
    "yarn.lock"
  ]);
  return entries
    .map((entry) => entry.name)
    .filter((name) => !name.startsWith("."))
    .filter((name) => !ignored.has(name));
}

async function listFilesRecursive(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const absolutePath = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      if (RECURSIVE_SOURCE_IGNORED_DIRECTORIES.has(entry.name)) {
        continue;
      }
      files.push(...(await listFilesRecursive(absolutePath)));
      continue;
    }
    files.push(absolutePath);
  }
  return files;
}

test("the application owns verification and uses exact JSKIT dependency specifiers", async () => {
  const packageJson = await readPackageJson();
  const runtimeDependencies = Object.entries(packageJson.dependencies || {}).filter(([name]) =>
    name.startsWith("@jskit-ai/")
  );
  const devDependencies = Object.entries(packageJson.devDependencies || {}).filter(([name]) =>
    name.startsWith("@jskit-ai/")
  );

  assert.ok(runtimeDependencies.length > 0, "Expected JSKIT runtime dependencies to be present.");
  assert.ok(devDependencies.length > 0, "Expected JSKIT dev dependencies to be present.");

  for (const [name, value] of [...runtimeDependencies, ...devDependencies]) {
    assert.match(value, /^\d+\.\d+\.\d+$/, `Expected ${name} to use an exact JSKIT version.`);
  }

  assert.equal(packageJson.devDependencies?.["@jskit-ai/jskit-cli"], undefined);
  assert.equal(packageJson.scripts?.["jskit:release"], undefined);

  for (const [scriptName, expectedValue] of Object.entries(EXPECTED_APPLICATION_SCRIPTS)) {
    assert.equal(packageJson.scripts?.[scriptName], expectedValue, `Unexpected ${scriptName} script.`);
  }
});

test("package release script publishes through the npm release helper", async () => {
  const packageJson = await readPackageJson();
  assert.equal(packageJson.scripts?.release, "node ./scripts/npm-release.js");
});

test("the application foundation files are present at the app root", async () => {
  const entries = await readTopLevelEntries();
  for (const requiredEntry of REQUIRED_TOP_LEVEL_ENTRIES) {
    assert.equal(entries.includes(requiredEntry), true, `Missing top-level application entry: ${requiredEntry}`);
  }
});

test("app-owned CI verifies the application on Node 26", async () => {
  const workflowSource = await readFile(
    path.join(APP_ROOT, ".github", "workflows", "jskit-verify.yml"),
    "utf8"
  );

  assert.match(workflowSource, /Vibe64-owned application verification/);
  assert.doesNotMatch(workflowSource, /Generated by JSKIT|npx jskit/u);
  assert.match(workflowSource, /name: Vibe64 Verify/);
  assert.match(workflowSource, /npm_config_engine_strict: "true"/);
  assert.match(workflowSource, /npm_config_strict_allow_scripts: "true"/);
  assert.match(workflowSource, /actions\/checkout@v7/);
  assert.match(workflowSource, /actions\/setup-node@v7/);
  assert.match(workflowSource, /node-version: 26/);
  assert.doesNotMatch(workflowSource, /id: database-migrations/);
  assert.doesNotMatch(workflowSource, /run: npm run db:migrate/);
  assert.match(workflowSource, /run: npm run verify/);
  await assert.rejects(
    access(path.join(APP_ROOT, ".github", "workflows", "vibe64-verify.yml")),
    /ENOENT/
  );
});

test("docs deployment follows successful Vibe64 verification on main", async () => {
  const workflowSource = await readFile(
    path.join(APP_ROOT, ".github", "workflows", "deploy-docs.yml"),
    "utf8"
  );

  assert.match(workflowSource, /workflows:\s*\n\s*- Vibe64 Verify/u);
  assert.match(workflowSource, /branches:\s*\n\s*- main/u);
  assert.match(workflowSource, /workflow_run\.conclusion == 'success'/u);
  assert.match(workflowSource, /workflow_run\.event == 'push'/u);
  assert.match(workflowSource, /ref: \$\{\{ github\.event\.workflow_run\.head_sha \}\}/u);
});

test("application foundation does not include the retired app.manifest contract", async () => {
  await assert.rejects(access(path.join(APP_ROOT, "framework/app.manifest.mjs")), /ENOENT/);
});

test("Playwright uses the direct managed-preview environment contract", async () => {
  const configSource = await readFile(path.join(APP_ROOT, "playwright.config.mjs"), "utf8");

  assert.match(configSource, /PLAYWRIGHT_BASE_URL/u);
  assert.match(configSource, /VIBE64_PLAYWRIGHT_STORAGE_STATE/u);
  assert.match(configSource, /VIBE64_LIVE_E2E/u);
  assert.match(configSource, /tests\/e2e\/support\/start-web-server\.mjs/u);
  assert.doesNotMatch(configSource, /node \.\/bin\/server\.js/u);
  assert.doesNotMatch(configSource, /@jskit-ai\/jskit-cli|createJskitPlaywrightConfig/u);
});

test("local package source avoids brittle deep relative imports", async () => {
  const packageSourceFiles = await listFilesRecursive(path.join(APP_ROOT, "packages"));
  const brittleImportPattern = /\bfrom\s+["'](?:\.\.\/){5,}[^"']+["']/;
  const serverLibImportPattern = /\bfrom\s+["'][^"']*server\/lib\//;

  for (const filePath of packageSourceFiles) {
    if (!filePath.endsWith(".js") && !filePath.endsWith(".mjs")) {
      continue;
    }
    const source = await readFile(filePath, "utf8");
    assert.equal(
      brittleImportPattern.test(source),
      false,
      `Found brittle deep relative import in ${path.relative(APP_ROOT, filePath)}`
    );
    assert.equal(
      serverLibImportPattern.test(source),
      false,
      `Found app-private server/lib import in ${path.relative(APP_ROOT, filePath)}`
    );
  }
});
