const VIBE64_SESSION_PRESENCE_CHANGED_EVENT = "vibe64.session.presence.changed";
const VIBE64_SESSION_PRESENCE_DEBOUNCE_MS = 250;
const VIBE64_SESSION_PRESENCE_HEARTBEAT_MS = 1_000;
const VIBE64_SESSION_PRESENCE_IDLE_MS = 3_000;

export {
  VIBE64_SESSION_PRESENCE_CHANGED_EVENT,
  VIBE64_SESSION_PRESENCE_DEBOUNCE_MS,
  VIBE64_SESSION_PRESENCE_HEARTBEAT_MS,
  VIBE64_SESSION_PRESENCE_IDLE_MS
};
