<?php
$root = getcwd();
$outputPath = getenv('AI_STUDIO_CODE_INDEX_PATH') ?: '.ai-studio/code-index.md';
$excludedDirs = [
    '.git' => true,
    '.ai-studio' => true,
    'bootstrap/cache' => true,
    'node_modules' => true,
    'storage' => true,
    'vendor' => true,
];

function aiStudioMarkdownPath($path) {
    return str_replace(DIRECTORY_SEPARATOR, '/', $path);
}

function aiStudioIsExcluded($relativePath, $excludedDirs) {
    $normalized = aiStudioMarkdownPath($relativePath);
    foreach ($excludedDirs as $dir => $_) {
        if ($normalized === $dir || strpos($normalized, $dir . '/') === 0 || strpos($normalized, '/' . $dir . '/') !== false) {
            return true;
        }
    }
    return false;
}

$files = [];
$directoryIterator = new RecursiveDirectoryIterator($root, FilesystemIterator::SKIP_DOTS);
$filterIterator = new RecursiveCallbackFilterIterator(
    $directoryIterator,
    function ($current) use ($root, $excludedDirs) {
        if (!$current->isDir()) {
            return true;
        }
        $relativePath = substr($current->getPathname(), strlen($root) + 1);
        return !aiStudioIsExcluded($relativePath, $excludedDirs);
    }
);
$iterator = new RecursiveIteratorIterator($filterIterator);

foreach ($iterator as $fileInfo) {
    if (!$fileInfo->isFile() || strtolower($fileInfo->getExtension()) !== 'php') {
        continue;
    }
    $absolutePath = $fileInfo->getPathname();
    $relativePath = substr($absolutePath, strlen($root) + 1);
    if (aiStudioIsExcluded($relativePath, $excludedDirs)) {
        continue;
    }
    $files[] = aiStudioMarkdownPath($relativePath);
}

sort($files, SORT_STRING);

$lines = [
    '# AI Studio Code Index',
    '',
    'Generated by the AI Studio Laravel/PHP adapter.',
    '',
    '## Files',
];
$declarationCount = 0;

foreach ($files as $relativePath) {
    $source = file_get_contents($root . DIRECTORY_SEPARATOR . str_replace('/', DIRECTORY_SEPARATOR, $relativePath));
    if ($source === false) {
        continue;
    }
    $declarations = [];
    $sourceLines = preg_split('/\R/u', $source);
    foreach ($sourceLines as $index => $line) {
        if (preg_match('/^\s*(?:(?:public|protected|private|static|final|abstract)\s+)*function\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(/u', $line, $match)) {
            $declarations[] = ['kind' => 'function', 'name' => $match[1], 'line' => $index + 1];
            continue;
        }
        if (preg_match('/^\s*(?:final\s+|abstract\s+)?(class|interface|trait|enum)\s+([A-Za-z_][A-Za-z0-9_]*)\b/u', $line, $match)) {
            $declarations[] = ['kind' => $match[1], 'name' => $match[2], 'line' => $index + 1];
        }
    }
    if (count($declarations) < 1) {
        continue;
    }
    $declarationCount += count($declarations);
    $lines[] = '';
    $lines[] = '### ' . $relativePath;
    foreach ($declarations as $declaration) {
        $lines[] = '- line ' . $declaration['line'] . ': ' . $declaration['kind'] . ' ' . $declaration['name'];
    }
}

if ($declarationCount < 1) {
    $lines[] = '';
    $lines[] = 'No PHP declarations were detected.';
}

$outputDir = dirname($outputPath);
if (!is_dir($outputDir)) {
    mkdir($outputDir, 0777, true);
}
file_put_contents($outputPath, implode("\n", $lines) . "\n");
echo "Wrote " . $outputPath . "\n";
